name: jupyterlab
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12,<3.13
  - jupyterlab>=4.4,<4.5
  - jupyter-server-proxy==4.3.0
  - bleach>5.0.0
  - certifi>=2022.12.7
  - Jinja2<3.1
  - jupyterlab-git==0.50.1
  - jupyter_server==2.6.0
  - mistune>=2.0.1
  - papermill~=2.6.0
  - requests>=2.20.0
  - setuptools>=65.5.1
  - virtualenv>=20.7.2
  - ipython>=8.10.0
  - tornado>=6.3.3
  - packaging>=22.0
  - jupyter-resource-usage>=1.0.0
  - pip
  - pip:
    - backports.tarfile # beacuse of https://github.com/SwissDataScienceCenter/renkulab-docker/issues/471
