api = "0.11"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"

[buildpack]
  id = "renku/pi-agent"
  name = "Pi coding agent Buildpack"
  version = "0.5.1"

[metadata]
  # Build with --env BP_RENKU_PI_VERSION=version to overwrite
  pi_version = "~0.75.4"
