api = "0.11"

[buildpack]
  id = "renku/r-micromamba"
  version = "0.4.0"
  name = "R via Micromamba Buildpack"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"
