# Buildpack API version
api = "0.11"

# Buildpack ID and metadata
[buildpack]
id = "renku/frontends"
version = "0.0.1"
name = "Frontend composite buildpack"
description = "The composite buildpack that defines build orders"

[[order]]
                                                     
  [[order.group]]
    id = "paketo-buildpacks/miniconda"
    version = "0.10.4"                   

  [[order.group]]
    id = "renku/jupyterlab"
    version = "0.0.1"

  [[order.group]]
    id = "renku/frontend-selector"
    version = "0.0.1"

[[order]]
  [[order.group]]
    id = "vscodium"
    version = "0.2.0"

  [[order.group]]
    id = "renku/frontend-selector"
    version = "0.0.1"

